{{- if and .Values.config.enabled .Values.config.addressPools }}
{{- range .Values.config.addressPools }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
  {{- range .addresses }}
    - {{ . | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
