{{- if and .Values.config.enabled .Values.config.l2Advertisements }}
{{- range .Values.config.l2Advertisements }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ipAddressPools:
  {{- range .ipAddressPools }}
    - {{ . }}
  {{- end }}
---
{{- end }}
{{- end }}
