{{- if and .Values.config.enabled .Values.config.l2Advertisements }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - lb-pool
{{- end }}
